# -*- coding: utf-8 -*-
"""Copy of Applied Tech. Project 9- Numpy Arrays I

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rO9y-F3MQrq9c8RwG98LWNf8uabnCC2G

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Python Lists I

 2. NumPy Arrays I

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

     https://colab.research.google.com/drive/1DW9BKNhyNGZbY_J0SgVrY-izYucN1B0E

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project9** format.

4. Now, write your code in the prescribed code cells.

---

#### Activity 1: Create a 3 X 3 Matrix

To create a 3x3 matrix with values ranging from 2 to 10.

**For Example**:

```
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
```

Follow the steps given below to achieve the desired result:

  - **Step 1**: Import `numpy` module.

  - **Step 2**: Use `arange()` function to create array of numbers from 2 to 10 and `reshape()` function to reshape your array into another array having 3 rows and 3 columns. Store this reshaped array in a variable `x`.

  - **Step 3**: Print variable `x` to get the output.
"""

# Write your code here
# Step 1: Importing numpy module
import numpy as np

# Step 2: Creating and reshaping the array
x = np.arange(2, 11).reshape(3, 3)

# Step 3: Printing the array
print(x)

"""---

#### Activity 2: Change Dimension of an Array and Convert the NumPy Array into a List

Write a program to change the dimension of an array (say `my_arr =[1, 2, 3, 4, 5, 6, 7, 8, 9]`) into a 3 X 3 (3 rows and 3 columns) array and convert this NumPy array into a list.

**For Example:**
```
Original array is [1 2 3 4 5 6 7 8 9]
Dimension is (9,)
Change array shape to (3, 3) -> 3 rows and 3 columns
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The data type of the converted variable is
 list
```
"""

# Write your code here
import numpy as np

# Define the original array
my_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape the array into a 3x3 matrix
my_arr_reshaped = np.reshape(my_arr, (3, 3))

# Convert the NumPy array to a list
my_list = my_arr_reshaped.tolist()

# Print the new list
print(my_list)

"""---

#### Activity 3: Find Square Root and Calculate the value of $c$

Write a program to perform following two tasks:
-  Print the square root of numbers in the list.
- Compute the value of $c$ in the equation $c=\sqrt(a^2 + b^2)$.

**For Example**:

```
list1 = [4, 16, 9, 1, 25]
[2   4    3   1    5 ]
If a=27
   b=39
The value of c =  47.43416490252569
```
**Hint:** Use `np.sqrt()` function.
"""

# Write your solution here
import numpy as np

# create a list of numbers
num_list = [4, 9, 16, 25, 36]

# convert list to numpy array
num_arr = np.array(num_list)

# compute square root of elements in array
sqrt_arr = np.sqrt(num_arr)
print("Square root of numbers in the list: ", sqrt_arr)

# compute the value of c
a = 3
b = 4
c = np.sqrt(a**2 + b**2)
print("Value of c in the equation c = sqrt(a^2 + b^2) is:", c)

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project9**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project9** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""